### ISSUE TITLE
Huawei VRP version V800 command prompt in configuration mode is different with VRP version V200

### ISSUE THREAD

**Issue by dptashnik** [scrapli/scrapli_community#117]
**Describe the bug**
Timed out sending input to device.

**To Reproduce**
1. Your script
```
from scrapli import Scrapli
my_device = {
   "host": "192.168.1.15",
   "auth_username": "lab",
   "auth_password": "lab",
   "platform":"huawei_vrp",
   "transport": "telnet"
}
conn = Scrapli(**my_device)
conn.open()
conn.send_config("snmp-server location LAB")
```
2. What you're connecting to (vendor, platform, version)
Vendor: Huawei
Platform: NE40E
Version: V800R012C00SPC300

**Expected behavior**
The "send_config" command sends the command to a device.

**Stack Trace**
```
nso@nso:~/python/set_location$ python3 scrapli_test.py
Traceback (most recent call last):
  File "scrapli_test.py", line 41, in <module>
    conn.send_config("snmp-server location LAB")
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/driver/network/sync_driver.py", line 572, in send_config
    multi_response = self.send_configs(
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/driver/network/sync_driver.py", line 511, in send_configs
    self.acquire_priv(desired_priv=resolved_privilege_level)
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/driver/network/sync_driver.py", line 165, in acquire_priv
    self._escalate(escalate_priv=target_priv)
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/driver/network/sync_driver.py", line 101, in _escalate
    self.channel.send_input(channel_input=escalate_priv.escalate)
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 280, in decorate
    return self._multiprocessing_timeout(
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 340, in _multiprocessing_timeout
    self._handle_timeout()
  File "/home/nso/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 316, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: timed out sending input to device
```
**OS (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - scrapli version: 2022.1.30
 - scrapli_community version: 2022.1.30

**Additional context**
I'm pretty sure, that the issue reason in the Huawei VRP version V800 command prompt. In VRP version V200, in configuration mode, it looks like an open square bracket, hostname, close square bracket, [hostname]. In VRP V800 tilde is added before the hostname [~hostname]. So the regexp doesn't catch this. In addition, the VRP800 behavior in configuration mode is Cisco IOS XR or Juniper JunOS style, you have to commit configuration changes. And if you have uncommitted changes, tilde in prompt changes to the asterisk symbol.
```
<hostname>sys
Enter system view, return user view with return command.
[~hostname]interface LoopBack 100
[*hostname-LoopBack100]commit 
Committing........done.
[~hostname-LoopBack100]
[~hostname]undo interface LoopBack 100
[*hostname]commit 
[~hostname]
```

**Comment by dptashnik** [comment]
hey Carl

Yep, i`ll try.

Dmitry

**Comment by carlmontanari** [comment]
closing, will follow up in the pr! (thanks!)
